# Generated by Django 5.1.6 on 2025-02-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="document",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(null=True, upload_to="videos/"),
        ),
    ]
